import * as XLSX from 'xlsx';

/**
 * Exports the complete Enterprise Sales & Operations Dashboard data into an Excel (.xlsx) workbook.
 * Creates multiple structured sheets:
 *  1. Executive KPI Overview
 *  2. Monthly Revenue Trajectory
 *  3. Sales Channel Mix
 *  4. Field Sales & Van Stock Holdings
 */
export const exportDashboardToExcel = (dashboardData) => {
  try {
    const wb = XLSX.utils.book_new();
    const timestamp = new Date().toLocaleString('en-IN');
    const metrics = dashboardData.metrics || {};
    const user = dashboardData.user || {};

    // ==========================================
    // SHEET 1: Executive KPI Overview
    // ==========================================
    const overviewData = [
      ['ENTERPRISE SALES & OPERATIONS DASHBOARD REPORT'],
      ['Generated On', timestamp],
      ['Generated By', `${user.name || 'Administrator'} (${user.role || 'Administrator'})`],
      ['User Contact', `${user.email || 'admin@salesforce.com'} | ${user.phone || '+91 98765 43210'}`],
      [], // blank row
      ['KPI Metric', 'Value', 'Status / Operational Note'],
      [
        'Total Sales Revenue', 
        metrics.total_sales_revenue || 0, 
        metrics.total_sales_revenue > 0 ? 'Recorded sales revenue' : 'No sales recorded yet'
      ],
      [
        'Total Collections', 
        metrics.total_collections || 0, 
        `Cash: ₹${(metrics.cash_collections || 0).toLocaleString('en-IN')} | UPI: ₹${(metrics.upi_collections || 0).toLocaleString('en-IN')}`
      ],
      [
        'Total Stock Inventory', 
        `${(metrics.total_stock_units || 0).toLocaleString('en-IN')} Units`, 
        `Valuation: ₹${(metrics.total_stock_valuation || 0).toLocaleString('en-IN')} (${metrics.warehouse_stock_units || 0} WH + ${metrics.van_stock_units || 0} Van)`
      ],
      [
        'Total Invoices / Orders', 
        metrics.total_orders_count || 0, 
        metrics.total_orders_count > 0 ? 'Active customer orders' : 'No orders punched yet'
      ],
      [
        'Total Outstanding Amount', 
        metrics.total_outstanding || 0, 
        metrics.total_outstanding === 0 ? 'Clear - No pending dues' : 'Pending payment recovery'
      ],
      [
        'Sales Target Attainment', 
        `${metrics.sales_target_attainment || 0}%`, 
        `Monthly Target: ₹${(metrics.sales_target_amount || 0).toLocaleString('en-IN')}`
      ],
      [
        'Active Field Sales Representatives', 
        (dashboardData.fieldRepresentatives || []).length, 
        (dashboardData.fieldRepresentatives || []).length > 0 ? 'Active on duty' : 'No field salesmen allocated today'
      ]
    ];

    const wsOverview = XLSX.utils.aoa_to_sheet(overviewData);
    wsOverview['!cols'] = [
      { wch: 35 },
      { wch: 20 },
      { wch: 45 }
    ];
    XLSX.utils.book_append_sheet(wb, wsOverview, 'Executive Overview');

    // ==========================================
    // SHEET 2: Monthly Revenue Trajectory
    // ==========================================
    const trajectoryHeader = ['Month Order', 'Month', 'Revenue (INR)', 'Status'];
    const trajectoryRows = (dashboardData.monthlyTrajectory || []).map((m, idx) => [
      idx + 1,
      m.month,
      m.revenue || 0,
      m.revenue > 0 ? 'Recorded' : 'Zero Base'
    ]);

    const wsTrajectory = XLSX.utils.aoa_to_sheet([trajectoryHeader, ...trajectoryRows]);
    wsTrajectory['!cols'] = [
      { wch: 15 },
      { wch: 15 },
      { wch: 22 },
      { wch: 20 }
    ];
    XLSX.utils.book_append_sheet(wb, wsTrajectory, 'Revenue Trajectory');

    // ==========================================
    // SHEET 3: Sales Channel Mix
    // ==========================================
    const channelHeader = ['Sales Channel Origin', 'Contribution %', 'Total Amount (INR)'];
    const channelRows = (dashboardData.channelMix || []).map(ch => [
      ch.channel,
      `${ch.percentage || 0}%`,
      ch.amount || 0
    ]);

    const wsChannel = XLSX.utils.aoa_to_sheet([channelHeader, ...channelRows]);
    wsChannel['!cols'] = [
      { wch: 28 },
      { wch: 18 },
      { wch: 25 }
    ];
    XLSX.utils.book_append_sheet(wb, wsChannel, 'Channel Mix');

    // ==========================================
    // SHEET 4: Field Sales & Van Stock Holdings
    // ==========================================
    const repsHeader = [
      'Sales Representative',
      'Phone Number',
      'Assigned Vehicle',
      'Assigned Locations',
      'Van Stock Items Count',
      'Van Stock Value (INR)',
      'Cash Collected (INR)',
      'Total Money In Hand (INR)',
      'Duty Status'
    ];

    let repRows = [];
    if (dashboardData.fieldRepresentatives && dashboardData.fieldRepresentatives.length > 0) {
      repRows = dashboardData.fieldRepresentatives.map(rep => [
        rep.name || 'N/A',
        rep.phone || '',
        rep.assigned_vehicle || '',
        rep.assigned_locations || '',
        rep.current_van_stock_items || 0,
        rep.van_stock_value || 0,
        rep.cash_collected || 0,
        rep.total_money_in_hand || 0,
        rep.duty_status || 'On Duty'
      ]);
    } else {
      repRows = [
        ['No active field salesmen allocated today.', '', '', '', '', '', '', '', '']
      ];
    }

    const wsReps = XLSX.utils.aoa_to_sheet([repsHeader, ...repRows]);
    wsReps['!cols'] = [
      { wch: 25 },
      { wch: 18 },
      { wch: 20 },
      { wch: 35 },
      { wch: 22 },
      { wch: 22 },
      { wch: 22 },
      { wch: 25 },
      { wch: 16 }
    ];
    XLSX.utils.book_append_sheet(wb, wsReps, 'Van Stock & Field Reps');

    // ==========================================
    // Trigger File Download as .xlsx
    // ==========================================
    const fileName = `Enterprise_Sales_Operations_${Date.now()}.xlsx`;
    XLSX.writeFile(wb, fileName);
    return { success: true, fileName };
  } catch (error) {
    console.error('Failed to export to Excel:', error);
    throw error;
  }
};
